### ISSUE TITLE
Sidebar Update: Implement Responsive and User-Friendly Changes

### ISSUE THREAD

**Issue by Pradeep717** [Pradeep717/OBE-BASED-STUDENT-MANAGEMENT-SYSTEM#6]

**Comment by saranga97** [comment]
Pushing necessary files to implement responsive and user-friendly changes for the sidebar. Tested and ready for review. Closing the issue as complete. Please feel free to provide feedback or further suggestions.

**Comment by saranga97** [comment]
Files added.
